import sys,re,subprocess;sys.path.insert(0,'build')
from fotopages import *
import fotopages as FP
ARR='<svg viewBox="0 0 24 24"><path d="M3 12h18M14 5l7 7-7 7"/></svg>'
def card(n,cat,name,price,photo,pos='50% 50%',size='cover',tag=None,disc=None):
    nw=f'<span style="{M};color:{T}">Nowość</span>' if tag else ''
    dc=f'<span style="{M};color:{T};margin-left:0">{disc}</span>' if disc else ''
    bd=f'<span style="position:absolute;top:0;left:0;background:#fff;color:{T};{M};font-size:12px;padding:5px 9px;box-shadow:0 0 0 1px #DCDCDC">{disc}</span>' if disc else ''
    return f'<div style="position:relative;display:flex;flex-direction:column;gap:8px"><div style="height:125px;background:url(/_blob/{photo}) {pos}/{size} no-repeat #CBCAC4">{bd}</div><div style="font-size:16px;font-weight:600;letter-spacing:-.02em;line-height:1.2;color:#111">{name}</div><div style="font-size:15px;color:#111;display:flex;align-items:baseline;flex-wrap:wrap;row-gap:2px;padding-right:44px;min-height:36px">{price}</div><span title="Dodaj do koszyka" aria-label="Dodaj do koszyka" style="position:absolute;right:0;bottom:0;width:34px;height:34px;background:#ED6842;display:flex;align-items:center;justify-content:center"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="#000" stroke-width="1.8" stroke-linecap="square"><path d="M2 3h3l2.6 12h11l2-8H6.2"/><circle cx="9" cy="20" r="1.4"/><circle cx="17" cy="20" r="1.4"/></svg></span></div>'
def p():
    o=lab('40 · Przyciski i komponenty')+h1('Przycisk jest prosty. Obietnica konkretna.',30)
    o+=f'<div style="border-top:2px solid {T};padding-top:12px;margin-top:14px"><div style="display:flex;gap:12px;flex-wrap:wrap"><div><a class="btn" href="#">Zamów próbki {ARR}</a><div class="mono" style="margin-top:6px">Główny</div></div><div><a class="btn nv" href="#">Zobacz realizacje {ARR}</a><div class="mono" style="margin-top:6px">Granatowy</div></div><div><a class="btn o" href="#">Pobierz katalog PDF</a><div class="mono" style="margin-top:6px">Obrys</div></div></div><div style="display:flex;gap:26px;align-items:center;margin-top:14px"><div><a class="lnk" href="#">Poproś o wycenę</a><div class="mono" style="margin-top:6px">Link tekstowy</div></div><div><div style="display:flex;gap:8px"><span class="tag mono">Wnętrza</span><span class="tag mono">Elewacje</span><span class="tag mono" style="border-color:#ED6842;color:#ED6842">Nowość</span></div><div class="mono" style="margin-top:6px">Etykiety</div></div></div></div>'
    o+=f'<div style="display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:12px"><div style="font-size:12.5px;line-height:1.45;color:#333"><div style="{M};color:{G};margin-bottom:3px">Stany</div>Hover zmienia przycisk główny na czarny; disabled: obrys szary #767676. Kąty proste, wysokość 52 px, bez zaokrągleń i cieni. Tekst czarny na pomarańczu (6,66:1).</div><div style="background:{B};padding:10px 14px;font-size:12.5px;line-height:1.45;color:#111"><div style="{M};color:{G};margin-bottom:3px">Język CTA</div>Tak: „Zamów próbki”, „Zobacz realizacje”, „Poproś o wycenę”. Nie: „Kliknij tutaj”, „Dowiedz się więcej!!!”.</div></div>'
    o+=f'<div style="margin-top:14px;border-top:2px solid {T};padding-top:10px">{sub("Karta produktu na liście",T,4)}'+para('Minimum informacji: zdjęcie, nazwa i cena. Rabat to biała etykieta w lewym górnym rogu zdjęcia. Cała karta jest klikalna, a jedynym CTA jest mała ikona koszyka w prawym dolnym rogu (z opisem „Dodaj do koszyka”). Karta nie może wyglądać jak dashboard.',0)+'</div>'
    cs=[card('014','Wnętrza','RETRO','<b style="font-weight:500;margin-right:4px">85,00</b> zł / m²','f13bfb534ccf00e0996ec45a24a078f5','50% 50%'),card('015','Wnętrza','RETRO PASTELOVE','<b style="font-weight:500;margin-right:4px">60,00</b> zł / m²<span style="font-size:13px;color:#767676;text-decoration:line-through;margin-left:10px">89,00 zł</span>','2220e7748909b98f052e7428974c361e','50% 50%',tag=1,disc='−33%'),card('016','Elewacje','RUSTYKALNE LOFT','<b style="font-weight:500;margin-right:4px">125,00</b> zł / m²','fdff6103d545d3549127f38239dd873c','50% 50%')]
    o+='<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:10px">'+''.join(cs)+'</div>'
    o+=f'<div style="margin-top:14px;border-top:2px solid {T};padding-top:10px">{sub("Baner kalkulatora",T,6)}<div style="background:{G};padding:16px 20px;display:flex;justify-content:space-between;align-items:center;gap:20px"><div><div style="{M};color:#fff;display:flex;gap:8px;align-items:center"><i style="display:block;width:8px;height:8px;background:{T}"></i>Kalkulator</div><div style="font-size:24px;font-weight:300;letter-spacing:-.03em;color:#fff;line-height:1.1;margin-top:6px">Oblicz potrzebną chemię</div><div style="font-size:12.5px;line-height:1.4;color:#fff;margin-top:4px;opacity:.9">Podaj powierzchnię, a dobierzemy klej, impregnat i fugę.</div></div><a class="btn" href="#" style="background:#fff;color:#111;border-color:#fff;flex:none">Oblicz ilość chemii {ARR}</a></div></div>'
    d=[('Co','Prostokątne przyciski i karty bez ozdób. Pomarańcz jako wypełnienie przycisku głównego.'),('Dlaczego','CTA ma być zauważalny, ale nie przykrywać zdjęcia.'),('Jak stosować','Jeden przycisk główny na widok (na kartach listy: ikona koszyka). Czasownik + konkret.'),('Czego unikać','Zaokrągleń, cieni, gradientów, białego tekstu na pomarańczu, kilku przycisków głównych obok siebie.')]
    o+=f'<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px 24px;margin-top:12px;border-top:1px solid {H};padding-top:10px">'+''.join(f'<div><div style="{M};color:{T if i==3 else G}">{a}</div><div style="font-size:12.5px;line-height:1.4;color:#333;margin-top:3px">{b}</div></div>' for i,(a,b) in enumerate(d))+'</div>'
    return o
def bottom(n):
    o=subprocess.run(['node','pag/fitabs.js','all/project',f'str-{n}.dc.html'],capture_output=True,text=True).stdout
    m=re.search(r'bottom: (\d+)',o);return int(m.group(1)) if m else 9999
n='065';pp=p();FP.mywrite(n,pp,1.0);b=bottom(n)
z=max(1.0,min(1.2,round(0.985*920/max(b-100,1),2)))
while True:
    FP.mywrite(n,pp,z);b=bottom(n)
    if b<=1022 or z<=1.0:break
    z=round(z-0.02,2)
print(z,b)
